### Dynamic Systems

Potentials x, model matrix A, voltage source b,,  we have
$$A^{T}C(b-Ax) = f $$
b is zero, since there is not potential source (aka volatage in electrical), we have
$$A^TCAx = f $$
say $A^TCA = K$, this is the Kirchkoff current term, then
$$Kx = f$$

### Network Problem

### Steady State Conduction

Transient conduction is essentially a network problem in dynamic systems.
If we have a 1D network with 4 nodes and 3 edges, for the incidence matrix $A$ the rows are the nodes and the columns are the edges. The arrow enters the node is 1 and leaves the node is -1.

In [6]:
import numpy as np

A = np.matrix('-1 0 0;1 -1 0;0 1 -1;0 0 1').T
print(A)

[[-1  1  0  0]
 [ 0 -1  1  0]
 [ 0  0 -1  1]]


In [7]:
u = np.array([10,20,30,40]).T
print(u)
dif = np.dot(A, u)
print(dif)

[10 20 30 40]
[[10 10 10]]


In [11]:
C = np.eye(3)*np.array([1,2,3])
print(C)

[[ 1.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  3.]]


In [12]:
K = np.dot(np.dot(A.T,C),A)
print(K)

[[ 1. -1.  0.  0.]
 [-1.  3. -2.  0.]
 [ 0. -2.  5. -3.]
 [ 0.  0. -3.  3.]]


In [13]:
x = np.array([10,10,10,40]).T
print()